package com.webstudio.lumagallery.ui.theme

import androidx.compose.ui.graphics.Color

// Luma liquid glass palette: cool crystal surfaces with aqua and warm coral accents.

// Light scheme
val LumaPrimaryLight = Color(0xFF006B7A)
val LumaOnPrimaryLight = Color(0xFFFFFFFF)
val LumaPrimaryContainerLight = Color(0xFFC7F5FF)
val LumaOnPrimaryContainerLight = Color(0xFF001F26)
val LumaSecondaryLight = Color(0xFF52606B)
val LumaOnSecondaryLight = Color(0xFFFFFFFF)
val LumaSecondaryContainerLight = Color(0xFFDCEAF3)
val LumaOnSecondaryContainerLight = Color(0xFF101D25)
val LumaTertiaryLight = Color(0xFF9A4E00)
val LumaOnTertiaryLight = Color(0xFFFFFFFF)
val LumaTertiaryContainerLight = Color(0xFFFFDCC3)
val LumaOnTertiaryContainerLight = Color(0xFF311300)
val LumaErrorLight = Color(0xFFBA1A1A)
val LumaOnErrorLight = Color(0xFFFFFFFF)
val LumaErrorContainerLight = Color(0xFFFFDAD6)
val LumaOnErrorContainerLight = Color(0xFF410002)
val LumaBackgroundLight = Color(0xFFF6FAFD)
val LumaOnBackgroundLight = Color(0xFF172026)
val LumaSurfaceLight = Color(0xFFF9FCFF)
val LumaOnSurfaceLight = Color(0xFF172026)
val LumaSurfaceVariantLight = Color(0xFFDDE7EE)
val LumaOnSurfaceVariantLight = Color(0xFF42515B)
val LumaSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val LumaSurfaceContainerLowLight = Color(0xFFF2F8FC)
val LumaSurfaceContainerLight = Color(0xFFEAF3F8)
val LumaSurfaceContainerHighLight = Color(0xFFE2EDF4)
val LumaSurfaceContainerHighestLight = Color(0xFFD9E6EE)
val LumaSurfaceTintLight = LumaPrimaryLight
val LumaInverseSurfaceLight = Color(0xFF2C343A)
val LumaInverseOnSurfaceLight = Color(0xFFEFF6FA)
val LumaInversePrimaryLight = Color(0xFF75D8E8)
val LumaOutlineLight = Color(0xFF73828C)
val LumaOutlineVariantLight = Color(0xFFC0CED6)
val LumaScrimLight = Color(0xFF000000)

// Dark scheme
val LumaPrimaryDark = Color(0xFF75D8E8)
val LumaOnPrimaryDark = Color(0xFF00363F)
val LumaPrimaryContainerDark = Color(0xFF004F5B)
val LumaOnPrimaryContainerDark = Color(0xFFC7F5FF)
val LumaSecondaryDark = Color(0xFFBFD0DA)
val LumaOnSecondaryDark = Color(0xFF24323A)
val LumaSecondaryContainerDark = Color(0xFF3A4851)
val LumaOnSecondaryContainerDark = Color(0xFFDCEAF3)
val LumaTertiaryDark = Color(0xFFFFB77D)
val LumaOnTertiaryDark = Color(0xFF512400)
val LumaTertiaryContainerDark = Color(0xFF743700)
val LumaOnTertiaryContainerDark = Color(0xFFFFDCC3)
val LumaErrorDark = Color(0xFFFFB4AB)
val LumaOnErrorDark = Color(0xFF690005)
val LumaErrorContainerDark = Color(0xFF93000A)
val LumaOnErrorContainerDark = Color(0xFFFFDAD6)
val LumaBackgroundDark = Color(0xFF0F171D)
val LumaOnBackgroundDark = Color(0xFFDDE7EE)
val LumaSurfaceDark = Color(0xFF121B21)
val LumaOnSurfaceDark = Color(0xFFDDE7EE)
val LumaSurfaceVariantDark = Color(0xFF3F4D56)
val LumaOnSurfaceVariantDark = Color(0xFFBFCBD3)
val LumaSurfaceContainerLowestDark = Color(0xFF0A1116)
val LumaSurfaceContainerLowDark = Color(0xFF182229)
val LumaSurfaceContainerDark = Color(0xFF1D2830)
val LumaSurfaceContainerHighDark = Color(0xFF26333B)
val LumaSurfaceContainerHighestDark = Color(0xFF31404A)
val LumaSurfaceTintDark = LumaPrimaryDark
val LumaInverseSurfaceDark = Color(0xFFDDE7EE)
val LumaInverseOnSurfaceDark = Color(0xFF2C343A)
val LumaInversePrimaryDark = Color(0xFF006B7A)
val LumaOutlineDark = Color(0xFF8998A2)
val LumaOutlineVariantDark = Color(0xFF3F4D56)
val LumaScrimDark = Color(0xFF000000)
